from __future__ import annotations

import re
import sqlite3
import threading
from pathlib import Path
from typing import (
    Any,
    Callable,
    Iterator,
    List,
    Mapping,
    NoReturn,
    Optional,
    Sequence,
    Set,
)

from blrec.networking.manager import NetworkRouteManager, RouteSelection
from blrec.networking.traffic import TrafficDirection

from .database import BiliUploadDatabase, DatabaseLocked

__all__ = (
    'POSTGRES_COMPATIBILITY_SQL',
    'PostgresBiliUploadDatabase',
    'create_bili_upload_database',
    'postgres_schema_sql',
    'postgres_sql',
)


_INSERT_TABLE = re.compile(
    r'^\s*INSERT\s+INTO\s+(?:"([^"]+)"|([A-Za-z_][A-Za-z0-9_]*))', re.I
)


def _raise_sqlite_compatible_error(error: Exception) -> NoReturn:
    import psycopg

    if isinstance(error, psycopg.IntegrityError):
        raise sqlite3.IntegrityError(str(error)) from error
    raise error


def _payload_size(value: Any) -> int:
    if value is None:
        return 0
    if isinstance(value, (bytes, bytearray, memoryview)):
        return len(value)
    if isinstance(value, str):
        return len(value.encode('utf8'))
    return len(str(value).encode('utf8'))


POSTGRES_COMPATIBILITY_SQL = """
CREATE COLLATION IF NOT EXISTS nocase (
    provider = icu,
    locale = 'und-u-ks-level2',
    deterministic = false
);

CREATE OR REPLACE FUNCTION instr(value text, needle text)
RETURNS integer LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT strpos(value, needle) $$;

CREATE OR REPLACE FUNCTION max(left_value anycompatible, right_value anycompatible)
RETURNS anycompatible LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT GREATEST(left_value, right_value) $$;

CREATE OR REPLACE FUNCTION min(left_value anycompatible, right_value anycompatible)
RETURNS anycompatible LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$ SELECT LEAST(left_value, right_value) $$;

CREATE OR REPLACE FUNCTION json_valid(value text)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
BEGIN
    PERFORM value::jsonb;
    RETURN true;
EXCEPTION WHEN others THEN
    RETURN false;
END
$$;

CREATE OR REPLACE FUNCTION blrec_group_concat_one(state text, value anyelement)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$
    SELECT CASE
        WHEN value IS NULL THEN state
        WHEN state IS NULL THEN value::text
        ELSE state || ',' || value::text
    END
$$;

CREATE OR REPLACE FUNCTION blrec_group_concat_delimited(
    state text, value anyelement, delimiter text
)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE
AS $$
    SELECT CASE
        WHEN value IS NULL THEN state
        WHEN state IS NULL THEN value::text
        ELSE state || delimiter || value::text
    END
$$;

DROP AGGREGATE IF EXISTS group_concat(anyelement);
DROP AGGREGATE IF EXISTS group_concat(anyelement, text);

CREATE AGGREGATE group_concat(anyelement) (
    SFUNC = blrec_group_concat_one,
    STYPE = text
);

CREATE AGGREGATE group_concat(anyelement, text) (
    SFUNC = blrec_group_concat_delimited,
    STYPE = text
);

CREATE OR REPLACE FUNCTION strftime(
    format text, unix_seconds bigint, epoch_modifier text, offset_modifier text
)
RETURNS text LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE
AS $$
    SELECT to_char(
        to_timestamp(unix_seconds) + CASE offset_modifier
            WHEN '+8 hours' THEN interval '8 hours'
            ELSE interval '0 seconds'
        END,
        replace(replace(replace(replace(replace(replace(
            format, '%Y', 'YYYY'), '%m', 'MM'), '%d', 'DD'),
            '%H', 'HH24'), '%M', 'MI'), '%S', 'SS')
    )
$$;
"""


def postgres_schema_sql(sql: str) -> str:
    statement = re.sub(
        r'\bINTEGER\s+PRIMARY\s+KEY\b',
        'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        sql,
        flags=re.I,
    )
    statement = re.sub(r'\bINTEGER\b', 'BIGINT', statement, flags=re.I)
    statement = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', statement, flags=re.I)
    statement = re.sub(r'\bBLOB\b', 'BYTEA', statement, flags=re.I)
    statement = re.sub(r'\bCOLLATE\s+NOCASE\b', 'COLLATE nocase', statement, flags=re.I)
    statement = re.sub(
        r"([A-Za-z_][A-Za-z0-9_.]*)\s+NOT\s+GLOB\s+" r"'\*\[\^([^]]+)\]\*'",
        r"\1 !~ '[^\2]'",
        statement,
        flags=re.I,
    )
    statement = re.sub(
        r"([A-Za-z_][A-Za-z0-9_.]*)\s+GLOB\s+'\*\.png'",
        r"\1 LIKE '%.png'",
        statement,
        flags=re.I,
    )
    statement = re.sub(r'\s+WITHOUT\s+ROWID\s*$', '', statement, flags=re.I)
    if re.match(r'^\s*CREATE\s+TABLE\b', statement, re.I):
        statement = re.sub(r'\boffset\b', '"offset"', statement, flags=re.I)
    if re.match(r'^\s*CREATE\s+(?:UNIQUE\s+)?INDEX\b', statement, re.I):
        statement = re.sub(
            r'(\bON\s+[A-Za-z_][A-Za-z0-9_]*\s*\()\s*' r'(CASE\s+WHEN\b.*?\bEND)(\s*,)',
            r'\1(\2)\3',
            statement,
            count=1,
            flags=re.I | re.S,
        )
    return statement


def _postgres_placeholders(sql: str) -> str:
    """Translate SQLite qmark placeholders without touching quoted question marks."""

    translated: List[str] = []
    index = 0
    quote = ''
    while index < len(sql):
        character = sql[index]
        following = sql[index + 1] if index + 1 < len(sql) else ''
        if quote:
            translated.append('%%' if character == '%' else character)
            if character == quote:
                if following == quote:
                    translated.append(following)
                    index += 1
                else:
                    quote = ''
        elif character in ("'", '"'):
            quote = character
            translated.append(character)
        elif character == '-' and following == '-':
            end = sql.find('\n', index + 2)
            if end < 0:
                translated.append(sql[index:])
                break
            translated.append(sql[index:end])
            index = end - 1
        elif character == '/' and following == '*':
            end = sql.find('*/', index + 2)
            if end < 0:
                translated.append(sql[index:])
                break
            translated.append(sql[index : end + 2])
            index = end + 1
        elif character == '?':
            translated.append('%s')
        elif character == '%':
            translated.append('%%')
        else:
            translated.append(character)
        index += 1
    return ''.join(translated)


def postgres_sql(sql: str) -> str:
    statement = sql.strip()
    if re.fullmatch(r'BEGIN\s+IMMEDIATE;?', statement, re.I):
        statement = 'BEGIN'
    ignored = re.match(r'^INSERT\s+OR\s+IGNORE\s+INTO\s+', statement, re.I)
    if ignored is not None:
        statement = re.sub(
            r'^INSERT\s+OR\s+IGNORE\s+INTO\s+', 'INSERT INTO ', statement, count=1
        )
        statement = statement.rstrip(';') + ' ON CONFLICT DO NOTHING'
    statement = re.sub(
        r'\s+INDEXED\s+BY\s+[A-Za-z_][A-Za-z0-9_]*', '', statement, flags=re.I
    )
    statement = re.sub(r'\bCROSS\s+JOIN\b', 'JOIN', statement, flags=re.I)
    statement = re.sub(r'\bIS\s+\?', 'IS NOT DISTINCT FROM ?', statement, flags=re.I)
    return _postgres_placeholders(statement)


class _PostgresRow(Mapping[str, Any]):
    def __init__(self, columns: Sequence[str], values: Sequence[Any]) -> None:
        self._columns = tuple(columns)
        self._values = tuple(values)
        self._mapping = dict(zip(self._columns, self._values))

    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return self._values[key]
        return self._mapping[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._columns)

    def __len__(self) -> int:
        return len(self._columns)


class _PostgresCursor:
    def __init__(
        self,
        cursor: Any,
        *,
        lastrowid: Optional[int] = None,
        traffic_recorder: Optional[Callable[[TrafficDirection, int], None]] = None,
    ) -> None:
        self._cursor = cursor
        self.lastrowid = lastrowid
        self._traffic_recorder = traffic_recorder

    @property
    def rowcount(self) -> int:
        return int(self._cursor.rowcount)

    def _row(self, values: Optional[Sequence[Any]]) -> Optional[_PostgresRow]:
        if values is None:
            return None
        if self._traffic_recorder is not None:
            self._traffic_recorder(
                'down', sum(_payload_size(value) for value in values)
            )
        columns = tuple(column.name for column in (self._cursor.description or ()))
        return _PostgresRow(columns, values)

    def fetchone(self) -> Optional[_PostgresRow]:
        return self._row(self._cursor.fetchone())

    def fetchall(self) -> List[_PostgresRow]:
        converted = [self._row(row) for row in self._cursor.fetchall()]
        assert all(row is not None for row in converted)
        return [row for row in converted if row is not None]

    def __iter__(self) -> Iterator[_PostgresRow]:
        for row in self._cursor:
            converted = self._row(row)
            assert converted is not None
            yield converted


class _PostgresConnection:
    dialect = 'postgresql'

    def __init__(
        self,
        connection: Any,
        identity_tables: Set[str],
        *,
        reconnect: Callable[[], Any],
        traffic_recorder: Optional[Callable[[TrafficDirection, int], None]] = None,
        failure_reporter: Optional[Callable[[], None]] = None,
    ) -> None:
        self._connection = connection
        self._identity_tables = identity_tables
        self._reconnect = reconnect
        self._traffic_recorder = traffic_recorder
        self._failure_reporter = failure_reporter
        self.total_changes = 0

    @property
    def in_transaction(self) -> bool:
        from psycopg.pq import TransactionStatus

        if self._connection.closed:
            return False
        return self._connection.info.transaction_status != TransactionStatus.IDLE

    def close(self) -> None:
        self._connection.close()

    def _require_connection(self) -> Any:
        if self._connection.closed:
            self._connection = self._reconnect()
        return self._connection

    def _record_upstream(self, statement: str, parameters: Sequence[Any]) -> None:
        if self._traffic_recorder is None:
            return
        size = len(statement.encode('utf8')) + sum(
            _payload_size(value) for value in parameters
        )
        self._traffic_recorder('up', size)

    def _handle_error(self, error: Exception) -> NoReturn:
        import psycopg

        if isinstance(error, (psycopg.OperationalError, psycopg.InterfaceError)):
            self._connection.close()
            if self._failure_reporter is not None:
                self._failure_reporter()
        _raise_sqlite_compatible_error(error)

    def execute(self, sql: str, parameters: Sequence[Any] = ()) -> _PostgresCursor:
        statement = postgres_sql(sql)
        table_match = _INSERT_TABLE.match(statement)
        table = (
            ''
            if table_match is None
            else next(value for value in table_match.groups() if value is not None)
        )
        returns_identity = (
            table in self._identity_tables
            and re.search(r'\bRETURNING\b', statement, re.I) is None
        )
        if returns_identity:
            statement = statement.rstrip(';') + ' RETURNING id'
        connection = self._require_connection()
        cursor = connection.cursor()
        self._record_upstream(statement, parameters)
        try:
            cursor.execute(statement, tuple(parameters))
        except Exception as error:
            self._handle_error(error)
        lastrowid: Optional[int] = None
        if returns_identity:
            row = cursor.fetchone()
            if row is not None:
                lastrowid = int(row[0])
                if self._traffic_recorder is not None:
                    self._traffic_recorder('down', _payload_size(row[0]))
        if cursor.rowcount > 0:
            self.total_changes += int(cursor.rowcount)
        return _PostgresCursor(
            cursor, lastrowid=lastrowid, traffic_recorder=self._traffic_recorder
        )

    def executemany(
        self, sql: str, parameters: Sequence[Sequence[Any]]
    ) -> _PostgresCursor:
        connection = self._require_connection()
        cursor = connection.cursor()
        flattened = tuple(tuple(values) for values in parameters)
        self._record_upstream(
            postgres_sql(sql), tuple(value for values in flattened for value in values)
        )
        try:
            cursor.executemany(postgres_sql(sql), flattened)
        except Exception as error:
            self._handle_error(error)
        if cursor.rowcount > 0:
            self.total_changes += int(cursor.rowcount)
        return _PostgresCursor(cursor, traffic_recorder=self._traffic_recorder)


class PostgresBiliUploadDatabase(BiliUploadDatabase):
    """PostgreSQL implementation preserving the repository's serialized writer."""

    dialect = 'postgresql'

    def __init__(self, target: str, *, local_state_path: str) -> None:
        super().__init__(local_state_path)
        self._target = target.replace('postgresql+psycopg://', 'postgresql://', 1)
        self._identity_tables: Set[str] = set()
        self._network_route_manager: Optional[NetworkRouteManager] = None
        self._route_selection: Optional[RouteSelection] = None

    def configure_network(self, manager: Optional[NetworkRouteManager]) -> None:
        self._network_route_manager = manager

    def _connect(self) -> Any:
        self._selection()
        try:
            import psycopg
        except ImportError as error:
            raise RuntimeError('PostgreSQL 数据库需要安装 psycopg 运行依赖') from error
        try:
            connection = psycopg.connect(self._target, autocommit=True)
        except (psycopg.OperationalError, psycopg.InterfaceError):
            self._report_network_failure()
            raise
        self._report_network_success()
        return connection

    def _selection(self) -> Optional[RouteSelection]:
        manager = self._network_route_manager
        if manager is None:
            return None
        selection = manager.select(
            'database', anonymous=False, affinity_key='postgres-main-database'
        )
        self._route_selection = selection
        return selection

    def _record_traffic(self, direction: TrafficDirection, byte_count: int) -> None:
        manager = self._network_route_manager
        selection = self._route_selection
        if manager is None or selection is None or byte_count <= 0:
            return
        manager.traffic_meter.record(
            selection.interface_name, 'database', direction, byte_count
        )

    def _report_network_failure(self) -> None:
        if (
            self._network_route_manager is not None
            and self._route_selection is not None
        ):
            self._network_route_manager.report_failure(
                'database', self._route_selection.interface_name
            )

    def _report_network_success(self) -> None:
        if (
            self._network_route_manager is not None
            and self._route_selection is not None
        ):
            self._network_route_manager.report_success(
                'database', self._route_selection.interface_name
            )

    def _writer_connection(self) -> Any:
        connection = self._connect()
        try:
            locked = connection.execute(
                "SELECT pg_try_advisory_lock(hashtext('blrec-main-database'))"
            ).fetchone()
            if locked is None or not bool(locked[0]):
                raise DatabaseLocked('upload database is already owned')
            version = connection.execute(
                'SELECT COALESCE(MAX(version),0) FROM schema_migrations'
            ).fetchone()
            current = 0 if version is None else int(version[0])
            if current != self.LATEST_SCHEMA_VERSION:
                raise RuntimeError(
                    'PostgreSQL schema version {} does not match required {}'.format(
                        current, self.LATEST_SCHEMA_VERSION
                    )
                )
            rows = connection.execute(
                "SELECT column_name,table_name FROM information_schema.columns "
                "WHERE table_schema=current_schema() AND column_name='id' "
                "AND (is_identity='YES' OR column_default LIKE 'nextval(%')"
            ).fetchall()
            self._identity_tables.update(str(row[1]) for row in rows)
            return connection
        except BaseException:
            connection.close()
            raise

    def _adapter(self, *, writer: bool) -> _PostgresConnection:
        connector = self._writer_connection if writer else self._connect
        return _PostgresConnection(
            connector(),
            self._identity_tables,
            reconnect=connector,
            traffic_recorder=self._record_traffic,
            failure_reporter=self._report_network_failure,
        )

    def _open_sync(self) -> None:
        self._connection = self._adapter(writer=True)  # type: ignore

    async def open_readonly(self) -> None:
        async with self._lifecycle_lock:
            if self._executor_closed:
                raise RuntimeError('database has been closed')
            if self._connection is not None:
                return
            await self._run(self._open_readonly_sync)

    def _open_readonly_sync(self) -> None:
        connection = self._adapter(writer=False)
        try:
            version = connection.execute(
                'SELECT COALESCE(MAX(version),0) FROM schema_migrations'
            ).fetchone()
            current = 0 if version is None else int(version[0])
            if current != self.LATEST_SCHEMA_VERSION:
                raise RuntimeError(
                    'PostgreSQL schema version {} does not match required {}'.format(
                        current, self.LATEST_SCHEMA_VERSION
                    )
                )
            self._connection = connection  # type: ignore
        except BaseException:
            connection.close()
            raise

    def _close_sync(self) -> None:
        connection, self._connection = self._connection, None
        if connection is not None:
            connection.close()

    def _close_read_connections_sync(self) -> None:
        with self._read_connections_lock:
            connections = tuple(self._read_connections.values())
            self._read_connections.clear()
        for connection in connections:
            connection.close()

    def _read_connection(self) -> Any:
        if self._connection is None:
            raise RuntimeError('database is not open')
        thread_id = threading.get_ident()
        with self._read_connections_lock:
            existing = self._read_connections.get(thread_id)
            if existing is not None:
                return existing
            connection = self._adapter(writer=False)
            self._read_connections[thread_id] = connection  # type: ignore
            return connection

    def _write_sync(self, operation: Any) -> Any:
        connection = self._require_connection()
        connection.execute('BEGIN')
        try:
            result = operation(connection)
            connection.execute('COMMIT')
            return result
        except BaseException:
            if connection.in_transaction:
                try:
                    connection.execute('ROLLBACK')
                except BaseException:
                    pass
            raise

    def _checkpoint_sync(self) -> None:
        self._require_connection().execute('SELECT 1').fetchone()

    def _table_columns_sync(self, table: str) -> Set[str]:
        rows = self._require_connection().execute(
            'SELECT column_name FROM information_schema.columns '
            'WHERE table_schema=current_schema() AND table_name=?',
            (table,),
        )
        return {str(row['column_name']) for row in rows}

    def _secure_database_files(self) -> None:
        return None

    async def table_names(self) -> Set[str]:
        rows = await self.fetchall(
            'SELECT table_name FROM information_schema.tables '
            "WHERE table_schema=current_schema() AND table_type='BASE TABLE'"
        )
        return {str(row['table_name']) for row in rows}


def create_bili_upload_database(
    target: str,
    *,
    local_state_path: Optional[str] = None,
    network_route_manager: Optional[NetworkRouteManager] = None,
) -> BiliUploadDatabase:
    normalized = target.strip()
    if normalized.startswith(('postgresql://', 'postgresql+psycopg://')):
        fallback = local_state_path or str(Path('/cfg') / 'blrec.sqlite3')
        database = PostgresBiliUploadDatabase(normalized, local_state_path=fallback)
        database.configure_network(network_route_manager)
        return database
    return BiliUploadDatabase(normalized)
