import fcntl
import os
import sqlite3
from datetime import datetime, timedelta, timezone
from pathlib import Path
from unittest.mock import Mock
from urllib.parse import urlsplit

import psycopg
import pytest
from psycopg import sql
from psycopg.conninfo import make_conninfo

from blrec.bili_upload.database import BiliUploadDatabase
from blrec.bili_upload.highlights import HighlightService
from blrec.bili_upload.journal import RecordingJournalBridge
from blrec.bili_upload.postgres_database import (
    POSTGRES_COMPATIBILITY_SQL,
    PostgresBiliUploadDatabase,
    postgres_schema_sql,
    postgres_sql,
)
from blrec.vainglory.repository import VaingloryRepository
from blrec.visitor_analytics.archive import VisitorAnalyticsArchive
from blrec.visitor_analytics.sls import VisitorAnalyticsConfig, VisitorAnalyticsQuery
from scripts.migrate_blrec_postgres_schema import (
    _migration_statements,
    migrate_postgres_schema,
)
from scripts.migrate_blrec_sqlite_to_postgres import _exclusive_source_lock, migrate


def test_postgres_migration_refuses_a_live_sqlite_writer(tmp_path: Path) -> None:
    source_path = tmp_path / 'blrec.sqlite3'
    source_path.touch()
    with open(str(source_path) + '.lock', 'a+b', buffering=0) as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        with pytest.raises(RuntimeError, match='still owned'):
            with _exclusive_source_lock(source_path):
                pass


def test_postgres_sql_translates_parameters_without_touching_quotes() -> None:
    assert postgres_sql("SELECT '?' AS literal,value FROM item WHERE id=?") == (
        "SELECT '?' AS literal,value FROM item WHERE id=%s"
    )


def test_postgres_sql_escapes_percent_literals() -> None:
    assert postgres_sql("SELECT 1 WHERE value LIKE 'live:%' AND id=?") == (
        "SELECT 1 WHERE value LIKE 'live:%%' AND id=%s"
    )


def test_postgres_sql_translates_insert_or_ignore() -> None:
    assert postgres_sql('INSERT OR IGNORE INTO item(id,name) VALUES(?,?)') == (
        'INSERT INTO item(id,name) VALUES(%s,%s) ON CONFLICT DO NOTHING'
    )


def test_postgres_sql_preserves_sqlite_null_safe_equality() -> None:
    assert postgres_sql('SELECT 1 FROM item WHERE value IS ? AND id=?') == (
        'SELECT 1 FROM item WHERE value IS NOT DISTINCT FROM %s AND id=%s'
    )


def test_postgres_sql_translates_immediate_transaction() -> None:
    assert postgres_sql('BEGIN IMMEDIATE') == 'BEGIN'


def test_postgres_sql_removes_sqlite_query_planner_hints() -> None:
    source = (
        'SELECT * FROM first INDEXED BY first_created_idx '
        'CROSS JOIN second ON second.first_id=first.id'
    )

    assert postgres_sql(source) == (
        'SELECT * FROM first JOIN second ON second.first_id=first.id'
    )


@pytest.mark.asyncio
async def test_postgres_readonly_open_does_not_claim_writer_lock(
    tmp_path: Path,
) -> None:
    database = PostgresBiliUploadDatabase(
        'postgresql://example.invalid/blrec',
        local_state_path=str(tmp_path / 'blrec.sqlite3'),
    )
    connection = Mock()
    connection.execute.return_value.fetchone.return_value = (
        database.LATEST_SCHEMA_VERSION,
    )
    adapter = Mock(return_value=connection)
    database._adapter = adapter  # type: ignore[method-assign]

    await database.open_readonly()
    try:
        adapter.assert_called_once_with(writer=False)
    finally:
        await database.close()


def test_postgres_schema_translates_sqlite_types_and_constraints() -> None:
    source = (
        'CREATE TABLE item(id INTEGER PRIMARY KEY,payload BLOB NOT NULL,'
        "fingerprint TEXT CHECK(fingerprint NOT GLOB '*[^0-9a-f]*'),"
        'score REAL,name TEXT COLLATE NOCASE)'
    )

    assert postgres_schema_sql(source) == (
        'CREATE TABLE item('
        'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        'payload BYTEA NOT NULL,'
        "fingerprint TEXT CHECK(fingerprint !~ '[^0-9a-f]'),"
        'score DOUBLE PRECISION,name TEXT COLLATE nocase)'
    )


def test_postgres_schema_wraps_case_expression_index() -> None:
    source = (
        'CREATE INDEX item_source_idx ON item('
        "CASE WHEN source_id IS NULL THEN 'item:'||id ELSE 'source:'||source_id END,"
        'created_at DESC)'
    )

    assert postgres_schema_sql(source) == (
        'CREATE INDEX item_source_idx ON item('
        "(CASE WHEN source_id IS NULL THEN 'item:'||id "
        "ELSE 'source:'||source_id END),created_at DESC)"
    )


def test_postgres_schema_migration_77_has_explicit_supported_statements() -> None:
    statements = tuple(_migration_statements(77))

    assert len(statements) == 5
    assert 'ADD COLUMN public_visible BIGINT' in statements[0]
    assert 'ADD COLUMN daily_limit_override_v2 BIGINT' in statements[1]
    assert 'ADD COLUMN daily_limit_override_v2 BIGINT' in statements[2]


def test_postgres_schema_migration_78_has_explicit_supported_statements() -> None:
    statements = tuple(_migration_statements(78))

    assert len(statements) == 2
    assert 'CREATE TABLE vainglory_remote_media_controls' in statements[0]
    assert 'downloads_per_interface BIGINT NOT NULL DEFAULT 3' in statements[0]


def test_postgres_schema_migration_79_has_global_match_deduplication_fields() -> None:
    statements = tuple(_migration_statements(79))

    assert len(statements) == 5
    assert 'ADD COLUMN content_fingerprint TEXT' in statements[0]
    assert 'GLOB' not in statements[0]
    assert 'ADD COLUMN duplicate_of_match_id BIGINT' in statements[1]
    assert 'ADD COLUMN duplicate_checked_at BIGINT' in statements[2]
    assert 'vainglory_matches_content_fingerprint_idx' in statements[3]
    assert 'vainglory_matches_duplicate_of_idx' in statements[4]


def test_postgres_schema_migration_80_has_duplicate_review_fields() -> None:
    statements = tuple(_migration_statements(80))

    assert len(statements) == 3
    assert 'ADD COLUMN duplicate_review_state TEXT' in statements[0]
    assert 'ADD COLUMN duplicate_review_fingerprint TEXT' in statements[1]
    assert 'vainglory_matches_duplicate_review_idx' in statements[2]


def test_postgres_schema_migration_81_has_afk_prediction_fields() -> None:
    statements = tuple(_migration_statements(81))

    assert len(statements) == 6
    assert 'ADD COLUMN afk_prediction_status TEXT' in statements[0]
    assert 'ADD COLUMN afk_prediction_probability DOUBLE PRECISION' in statements[1]
    assert 'ADD COLUMN afk_prediction_model_version TEXT' in statements[2]
    assert 'ADD COLUMN afk_prediction_gate_reason TEXT' in statements[3]
    assert 'ADD COLUMN afk_manual_override BIGINT' in statements[4]
    assert 'vainglory_match_players_afk_prediction_idx' in statements[5]


def test_postgres_schema_migration_82_has_afk_backfill_queue() -> None:
    statements = tuple(_migration_statements(82))

    assert len(statements) == 4
    assert 'ADD COLUMN afk_detection_version BIGINT' in statements[0]
    assert 'CREATE TABLE vainglory_afk_backfill_jobs' in statements[1]
    assert 'vainglory_afk_backfill_jobs_claim_idx' in statements[2]
    assert 'INSERT INTO vainglory_afk_backfill_jobs' in statements[3]


def test_postgres_schema_migration_83_has_hero_prediction_probability() -> None:
    statements = tuple(_migration_statements(83))

    assert len(statements) == 1
    assert 'ADD COLUMN hero_prediction_probability DOUBLE PRECISION' in statements[0]


def test_postgres_schema_migration_77_repairs_privacy_and_extends_daily_limit() -> None:
    database_url = os.environ.get('BLREC_TEST_POSTGRES_URL', '').strip()
    if not database_url:
        pytest.skip('BLREC_TEST_POSTGRES_URL is not configured')
    database_name = urlsplit(database_url).path.lstrip('/')
    assert database_name == 'blrec_core_test'
    schema = 'core_migration_77'
    with psycopg.connect(database_url, autocommit=True) as connection:
        connection.execute(
            sql.SQL('DROP SCHEMA IF EXISTS {} CASCADE').format(sql.Identifier(schema))
        )
        connection.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(schema)))
    schema_url = make_conninfo(database_url, options='-csearch_path={}'.format(schema))
    try:
        with psycopg.connect(schema_url, autocommit=True) as connection:
            connection.execute(
                'CREATE FUNCTION instr(value text,needle text) RETURNS integer '
                'LANGUAGE sql IMMUTABLE STRICT AS '
                '$$ SELECT strpos(value,needle) $$'
            )
            connection.execute(
                'CREATE TABLE schema_migrations('
                'version BIGINT PRIMARY KEY,applied_at BIGINT NOT NULL)'
            )
            connection.execute('INSERT INTO schema_migrations VALUES(76,1)')
            connection.execute(
                'CREATE TABLE vainglory_players(id BIGINT PRIMARY KEY,name TEXT)'
            )
            connection.execute(
                'CREATE TABLE vainglory_archive_syncs('
                'account_id BIGINT PRIMARY KEY,daily_limit BIGINT NOT NULL,'
                'daily_limit_override BIGINT)'
            )
            connection.execute(
                'CREATE TABLE archive_migration_jobs('
                'id BIGINT PRIMARY KEY,daily_limit BIGINT NOT NULL,'
                'daily_limit_override BIGINT)'
            )
            connection.execute(
                'CREATE TABLE upload_jobs('
                'id BIGINT PRIMARY KEY,policy_snapshot_json TEXT)'
            )
            connection.execute(
                'CREATE TABLE vainglory_matches('
                'id BIGINT PRIMARY KEY,created_at BIGINT NOT NULL,'
                'result_frame_path TEXT)'
            )
            connection.execute(
                'CREATE TABLE vainglory_match_players('
                'id BIGINT PRIMARY KEY,match_id BIGINT NOT NULL)'
            )
            connection.execute(
                'CREATE TABLE vainglory_archive_imports('
                'id BIGINT PRIMARY KEY,account_id BIGINT,bvid TEXT,'
                'is_only_self BIGINT)'
            )
            connection.execute(
                'CREATE TABLE vainglory_publications('
                'id BIGINT PRIMARY KEY,account_id BIGINT,upload_job_id BIGINT,'
                'bvid TEXT,source_kind TEXT,visibility_scope TEXT,'
                'visibility_verified_at BIGINT,public_visible_at BIGINT,'
                'updated_at BIGINT)'
            )
            connection.execute("INSERT INTO vainglory_players VALUES(1,'玩家')")
            connection.execute('INSERT INTO vainglory_archive_syncs VALUES(1,500,1000)')
            connection.execute('INSERT INTO archive_migration_jobs VALUES(1,500,1000)')
            connection.execute(
                "INSERT INTO upload_jobs VALUES(1,'{ \"is_only_self\": true }')"
            )
            connection.execute(
                "INSERT INTO vainglory_archive_imports " "VALUES(1,2,'BV1archive01',1)"
            )
            connection.execute(
                'INSERT INTO vainglory_publications VALUES('
                "1,1,1,'BV1upload001','upload','public',2,2,2),"
                "(2,2,NULL,'BV1archive01','archive','public',3,3,3)"
            )

        assert migrate_postgres_schema(
            schema_url, expected_database=database_name, expected_schema=schema
        ) == (77, 78, 79, 80, 81, 82, 83)

        with psycopg.connect(schema_url, autocommit=True) as connection:
            assert connection.execute(
                'SELECT public_visible FROM vainglory_players WHERE id=1'
            ).fetchone() == (1,)
            connection.execute(
                'UPDATE vainglory_archive_syncs '
                'SET daily_limit_override_v2=50000 WHERE account_id=1'
            )
            assert connection.execute(
                'SELECT daily_limit_override_v2 FROM vainglory_archive_syncs '
                'WHERE account_id=1'
            ).fetchone() == (50000,)
            connection.execute(
                'UPDATE archive_migration_jobs '
                'SET daily_limit_override_v2=50000 WHERE id=1'
            )
            assert connection.execute(
                'SELECT daily_limit_override_v2 FROM archive_migration_jobs '
                'WHERE id=1'
            ).fetchone() == (50000,)
            assert connection.execute(
                'SELECT visibility_scope,public_visible_at '
                'FROM vainglory_publications ORDER BY id'
            ).fetchall() == [('owner', None), ('owner', None)]
            assert connection.execute(
                'SELECT MAX(version) FROM schema_migrations'
            ).fetchone() == (83,)
            columns = {
                row[0]
                for row in connection.execute(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema=current_schema() "
                    "AND table_name='vainglory_matches'"
                ).fetchall()
            }
            assert {
                'content_fingerprint',
                'duplicate_of_match_id',
                'duplicate_checked_at',
                'duplicate_review_state',
                'duplicate_review_fingerprint',
            } <= columns
    finally:
        with psycopg.connect(database_url, autocommit=True) as connection:
            connection.execute(
                sql.SQL('DROP SCHEMA IF EXISTS {} CASCADE').format(
                    sql.Identifier(schema)
                )
            )


@pytest.mark.asyncio
async def test_postgres_backend_migrates_schema_and_preserves_writes(
    tmp_path: Path,
) -> None:
    database_url = os.environ.get('BLREC_TEST_POSTGRES_URL', '').strip()
    if not database_url:
        pytest.skip('BLREC_TEST_POSTGRES_URL is not configured')
    database_name = urlsplit(database_url).path.lstrip('/')
    assert database_name == 'blrec_core_test'
    source_path = tmp_path / 'blrec.sqlite3'
    source = BiliUploadDatabase(str(source_path))
    await source.open()
    await source.close()
    with psycopg.connect(database_url, autocommit=True) as connection:
        connection.execute('CREATE SCHEMA core')
    core_database_url = make_conninfo(database_url, options='-csearch_path=core')

    copied = migrate(
        source_path,
        core_database_url,
        expected_database=database_name,
        expected_schema='core',
        backup_directory=tmp_path / 'backups',
    )
    assert len(copied) == 71
    with psycopg.connect(core_database_url, autocommit=True) as connection:
        connection.execute(POSTGRES_COMPATIBILITY_SQL)

    target = PostgresBiliUploadDatabase(
        core_database_url, local_state_path=str(source_path)
    )
    await target.open()
    try:
        before = int(
            await target.scalar(
                'SELECT revision FROM dashboard_source_state WHERE singleton_id=1'
            )
        )
        assert await target.scalar('SELECT MAX(?,?)', (3, 7)) == 7
        assert await target.scalar('SELECT MIN(?,?)', (3, 7)) == 3
        assert await target.scalar('SELECT MAX(NULL,?)', (7,)) is None
        assert await target.scalar('SELECT TRUE OR ?', (True,)) is True

        def insert_player(connection: sqlite3.Connection) -> int:
            cursor = connection.execute(
                'INSERT INTO vainglory_players('
                'name,origin,created_at,updated_at) VALUES(?,?,?,?)',
                ('PostgreSQL Probe', 'manual', 1, 1),
            )
            assert cursor.lastrowid is not None
            return int(cursor.lastrowid)

        player_id = await target.write(insert_player)
        inserted = int(
            await target.scalar(
                'SELECT revision FROM dashboard_source_state WHERE singleton_id=1'
            )
        )
        assert inserted == before + 1
        await target.execute('DELETE FROM vainglory_players WHERE id=?', (player_id,))
        deleted = int(
            await target.scalar(
                'SELECT revision FROM dashboard_source_state WHERE singleton_id=1'
            )
        )
        assert deleted == inserted + 1

        await target.execute(
            'INSERT INTO bili_accounts('
            'id,uid,display_name,credential_ciphertext,credential_version,key_id,'
            'state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',
            (101, 101, 'PostgreSQL Probe', b'probe', 1, 'probe', 'active', 1, 1),
        )
        await target.execute(
            'INSERT INTO recording_sessions('
            'id,room_id,broadcast_session_key,state,started_at) '
            'VALUES(?,?,?,?,?)',
            (202, 202, 'postgres-probe', 'closed', 1),
        )
        await target.execute(
            'INSERT INTO upload_jobs('
            'id,session_id,account_id,policy_snapshot_json,state,submit_state,'
            'created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',
            (303, 202, 101, '{}', 'ready', 'prepared', 1, 1),
        )
        claim = await target.claim('upload_jobs', ('ready',), 'postgres-probe', now=2)
        assert claim is not None
        assert claim.id == 303
        await target.fenced_update(
            'upload_jobs',
            claim.id,
            claim.lease_owner,
            claim.lease_generation,
            {'priority': 9},
        )
        assert (
            await target.scalar(
                'SELECT priority FROM upload_jobs WHERE id=?', (claim.id,)
            )
            == 9
        )
        summaries = await RecordingJournalBridge(target).list_session_summaries(
            limit=5, offset=0
        )
        assert len(summaries) == 1
        clip_total, clips = await HighlightService(target).list_clip_summaries(
            limit=5, offset=0
        )
        assert clip_total == 0
        assert clips == ()
        group_total, groups = await HighlightService(target).list_clip_groups(
            limit=5, offset=0
        )
        assert group_total == 0
        assert groups == ()
        vainglory = VaingloryRepository(target)
        match_sessions = await vainglory.list_match_sessions(
            session_id=202, limit=5, offset=0
        )
        assert match_sessions.total == 1
        assert len(match_sessions.items) == 1
        assert await vainglory.recover_interrupted() == 0
        await vainglory.register_analysis_worker(
            'postgres-probe-worker',
            model_package_id='package-v1',
            pipeline_version='pipeline-v1',
            concurrency=3,
        )
        registered_worker = await vainglory.register_analysis_worker(
            'postgres-probe-worker'
        )
        assert registered_worker.model_package_id == 'package-v1'
        assert registered_worker.pipeline_version == 'pipeline-v1'
        assert registered_worker.concurrency == 3
        configured_worker = await vainglory.update_analysis_worker(
            'postgres-probe-worker', desired_concurrency=4
        )
        assert configured_worker.desired_concurrency == 4
        await target.execute(
            'INSERT INTO recording_runs(id,session_id,state,started_at,ended_at) '
            'VALUES(?,?,?,?,?)',
            ('postgres-probe-run', 202, 'finished', 1, 2),
        )
        await target.execute(
            'INSERT INTO recording_parts('
            'id,session_id,run_id,part_index,source_path,record_start_time,'
            'artifact_state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',
            (
                404,
                202,
                'postgres-probe-run',
                1,
                '/tmp/postgres-probe.flv',
                1,
                'ready',
                1,
                1,
            ),
        )
        await target.execute(
            'INSERT INTO vainglory_part_jobs('
            'part_id,session_id,state,request_kind,progress,algorithm_version,'
            'match_count,error,requested_at,started_at,completed_at,updated_at) '
            'VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',
            (
                404,
                202,
                'pending',
                'manual',
                0,
                vainglory.ALGORITHM_VERSION,
                0,
                None,
                1,
                None,
                None,
                1,
            ),
        )
        await target.execute(
            'INSERT INTO vainglory_manual_match_markers('
            'id,session_id,part_id,at_ms,source,created_at,updated_at) '
            'VALUES(?,?,?,?,?,?,?)',
            (501, 202, 404, 900, 'dashboard', 1, 1),
        )
        await target.execute(
            'INSERT INTO vainglory_manual_match_markers('
            'id,session_id,part_id,at_ms,source,created_at,updated_at) '
            'VALUES(?,?,?,?,?,?,?)',
            (502, 202, 404, 100, 'dashboard', 1, 1),
        )
        scan_claim = await vainglory.claim_next(discover=False)
        assert scan_claim is not None
        assert scan_claim.part.manual_candidate_times_ms == (100, 900)
        await target.execute(
            'INSERT INTO vainglory_ocr_jobs('
            'part_id,session_id,state,video_duration_ms,candidate_times_json,'
            'candidate_count,requested_at,started_at,updated_at) '
            "VALUES(?,?,\'pending\',?,?,?,?,NULL,?)",
            (404, 202, 1_000, '[100]', 1, 1, 1),
        )
        ocr_claim = await vainglory.claim_next_ocr()
        assert ocr_claim is not None
        assert ocr_claim.part.id == 404
        archive = VisitorAnalyticsArchive(target)
        archive_status = await archive.status()
        now = datetime.now(timezone.utc)
        archive_summary = await archive.summary(
            VisitorAnalyticsQuery(
                start_at=now - timedelta(days=1), end_at=now, event='all'
            ),
            VisitorAnalyticsConfig(None, None),
            generated_at=now,
            status=archive_status,
        )
        assert archive_summary.totals.events == 0
        with pytest.raises(sqlite3.IntegrityError):
            await target.execute(
                'INSERT INTO vainglory_players('
                'name,origin,created_at,updated_at) VALUES(?,?,?,?)',
                (' invalid ', 'manual', 1, 1),
            )
    finally:
        await target.close()
