import fcntl
import os
import sqlite3
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlsplit

import psycopg
import pytest
from psycopg.conninfo import make_conninfo

from blrec.bili_upload.database import BiliUploadDatabase
from blrec.bili_upload.highlights import HighlightService
from blrec.bili_upload.journal import RecordingJournalBridge
from blrec.bili_upload.postgres_database import (
    POSTGRES_COMPATIBILITY_SQL,
    PostgresBiliUploadDatabase,
    postgres_schema_sql,
    postgres_sql,
)
from blrec.vainglory.repository import VaingloryRepository
from blrec.visitor_analytics.archive import VisitorAnalyticsArchive
from blrec.visitor_analytics.sls import VisitorAnalyticsConfig, VisitorAnalyticsQuery
from scripts.migrate_blrec_sqlite_to_postgres import _exclusive_source_lock, migrate


def test_postgres_migration_refuses_a_live_sqlite_writer(tmp_path: Path) -> None:
    source_path = tmp_path / 'blrec.sqlite3'
    source_path.touch()
    with open(str(source_path) + '.lock', 'a+b', buffering=0) as lock_file:
        fcntl.flock(lock_file.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        with pytest.raises(RuntimeError, match='still owned'):
            with _exclusive_source_lock(source_path):
                pass


def test_postgres_sql_translates_parameters_without_touching_quotes() -> None:
    assert postgres_sql("SELECT '?' AS literal,value FROM item WHERE id=?") == (
        "SELECT '?' AS literal,value FROM item WHERE id=%s"
    )


def test_postgres_sql_escapes_percent_literals() -> None:
    assert postgres_sql("SELECT 1 WHERE value LIKE 'live:%' AND id=?") == (
        "SELECT 1 WHERE value LIKE 'live:%%' AND id=%s"
    )


def test_postgres_sql_translates_insert_or_ignore() -> None:
    assert postgres_sql('INSERT OR IGNORE INTO item(id,name) VALUES(?,?)') == (
        'INSERT INTO item(id,name) VALUES(%s,%s) ON CONFLICT DO NOTHING'
    )


def test_postgres_sql_preserves_sqlite_null_safe_equality() -> None:
    assert postgres_sql('SELECT 1 FROM item WHERE value IS ? AND id=?') == (
        'SELECT 1 FROM item WHERE value IS NOT DISTINCT FROM %s AND id=%s'
    )


def test_postgres_sql_translates_immediate_transaction() -> None:
    assert postgres_sql('BEGIN IMMEDIATE') == 'BEGIN'


def test_postgres_sql_removes_sqlite_query_planner_hints() -> None:
    source = (
        'SELECT * FROM first INDEXED BY first_created_idx '
        'CROSS JOIN second ON second.first_id=first.id'
    )

    assert postgres_sql(source) == (
        'SELECT * FROM first JOIN second ON second.first_id=first.id'
    )


def test_postgres_schema_translates_sqlite_types_and_constraints() -> None:
    source = (
        'CREATE TABLE item(id INTEGER PRIMARY KEY,payload BLOB NOT NULL,'
        "fingerprint TEXT CHECK(fingerprint NOT GLOB '*[^0-9a-f]*'),"
        'score REAL,name TEXT COLLATE NOCASE)'
    )

    assert postgres_schema_sql(source) == (
        'CREATE TABLE item('
        'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,'
        'payload BYTEA NOT NULL,'
        "fingerprint TEXT CHECK(fingerprint !~ '[^0-9a-f]'),"
        'score DOUBLE PRECISION,name TEXT COLLATE nocase)'
    )


def test_postgres_schema_wraps_case_expression_index() -> None:
    source = (
        'CREATE INDEX item_source_idx ON item('
        "CASE WHEN source_id IS NULL THEN 'item:'||id ELSE 'source:'||source_id END,"
        'created_at DESC)'
    )

    assert postgres_schema_sql(source) == (
        'CREATE INDEX item_source_idx ON item('
        "(CASE WHEN source_id IS NULL THEN 'item:'||id "
        "ELSE 'source:'||source_id END),created_at DESC)"
    )


@pytest.mark.asyncio
async def test_postgres_backend_migrates_schema_and_preserves_writes(
    tmp_path: Path,
) -> None:
    database_url = os.environ.get('BLREC_TEST_POSTGRES_URL', '').strip()
    if not database_url:
        pytest.skip('BLREC_TEST_POSTGRES_URL is not configured')
    database_name = urlsplit(database_url).path.lstrip('/')
    assert database_name == 'blrec_core_test'
    source_path = tmp_path / 'blrec.sqlite3'
    source = BiliUploadDatabase(str(source_path))
    await source.open()
    await source.close()
    with psycopg.connect(database_url, autocommit=True) as connection:
        connection.execute('CREATE SCHEMA core')
    core_database_url = make_conninfo(database_url, options='-csearch_path=core')

    copied = migrate(
        source_path,
        core_database_url,
        expected_database=database_name,
        expected_schema='core',
        backup_directory=tmp_path / 'backups',
    )
    assert len(copied) == 69
    with psycopg.connect(core_database_url, autocommit=True) as connection:
        connection.execute(POSTGRES_COMPATIBILITY_SQL)

    target = PostgresBiliUploadDatabase(
        core_database_url, local_state_path=str(source_path)
    )
    await target.open()
    try:
        before = int(
            await target.scalar(
                'SELECT revision FROM dashboard_source_state WHERE singleton_id=1'
            )
        )
        assert await target.scalar('SELECT MAX(?,?)', (3, 7)) == 7
        assert await target.scalar('SELECT MIN(?,?)', (3, 7)) == 3
        assert await target.scalar('SELECT MAX(NULL,?)', (7,)) is None
        assert await target.scalar('SELECT TRUE OR ?', (True,)) is True

        def insert_player(connection: sqlite3.Connection) -> int:
            cursor = connection.execute(
                'INSERT INTO vainglory_players('
                'name,origin,created_at,updated_at) VALUES(?,?,?,?)',
                ('PostgreSQL Probe', 'manual', 1, 1),
            )
            assert cursor.lastrowid is not None
            return int(cursor.lastrowid)

        player_id = await target.write(insert_player)
        inserted = int(
            await target.scalar(
                'SELECT revision FROM dashboard_source_state WHERE singleton_id=1'
            )
        )
        assert inserted == before + 1
        await target.execute('DELETE FROM vainglory_players WHERE id=?', (player_id,))
        deleted = int(
            await target.scalar(
                'SELECT revision FROM dashboard_source_state WHERE singleton_id=1'
            )
        )
        assert deleted == inserted + 1

        await target.execute(
            'INSERT INTO bili_accounts('
            'id,uid,display_name,credential_ciphertext,credential_version,key_id,'
            'state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',
            (101, 101, 'PostgreSQL Probe', b'probe', 1, 'probe', 'active', 1, 1),
        )
        await target.execute(
            'INSERT INTO recording_sessions('
            'id,room_id,broadcast_session_key,state,started_at) '
            'VALUES(?,?,?,?,?)',
            (202, 202, 'postgres-probe', 'closed', 1),
        )
        await target.execute(
            'INSERT INTO upload_jobs('
            'id,session_id,account_id,policy_snapshot_json,state,submit_state,'
            'created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)',
            (303, 202, 101, '{}', 'ready', 'prepared', 1, 1),
        )
        claim = await target.claim('upload_jobs', ('ready',), 'postgres-probe', now=2)
        assert claim is not None
        assert claim.id == 303
        await target.fenced_update(
            'upload_jobs',
            claim.id,
            claim.lease_owner,
            claim.lease_generation,
            {'priority': 9},
        )
        assert (
            await target.scalar(
                'SELECT priority FROM upload_jobs WHERE id=?', (claim.id,)
            )
            == 9
        )
        summaries = await RecordingJournalBridge(target).list_session_summaries(
            limit=5, offset=0
        )
        assert len(summaries) == 1
        clip_total, clips = await HighlightService(target).list_clip_summaries(
            limit=5, offset=0
        )
        assert clip_total == 0
        assert clips == ()
        group_total, groups = await HighlightService(target).list_clip_groups(
            limit=5, offset=0
        )
        assert group_total == 0
        assert groups == ()
        vainglory = VaingloryRepository(target)
        match_sessions = await vainglory.list_match_sessions(
            session_id=202, limit=5, offset=0
        )
        assert match_sessions.total == 1
        assert len(match_sessions.items) == 1
        assert await vainglory.recover_interrupted() == 0
        await vainglory.register_analysis_worker(
            'postgres-probe-worker',
            model_package_id='package-v1',
            pipeline_version='pipeline-v1',
            concurrency=3,
        )
        registered_worker = await vainglory.register_analysis_worker(
            'postgres-probe-worker'
        )
        assert registered_worker.model_package_id == 'package-v1'
        assert registered_worker.pipeline_version == 'pipeline-v1'
        assert registered_worker.concurrency == 3
        configured_worker = await vainglory.update_analysis_worker(
            'postgres-probe-worker', desired_concurrency=4
        )
        assert configured_worker.desired_concurrency == 4
        await target.execute(
            'INSERT INTO recording_runs(id,session_id,state,started_at,ended_at) '
            'VALUES(?,?,?,?,?)',
            ('postgres-probe-run', 202, 'finished', 1, 2),
        )
        await target.execute(
            'INSERT INTO recording_parts('
            'id,session_id,run_id,part_index,source_path,record_start_time,'
            'artifact_state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)',
            (
                404,
                202,
                'postgres-probe-run',
                1,
                '/tmp/postgres-probe.flv',
                1,
                'ready',
                1,
                1,
            ),
        )
        await target.execute(
            'INSERT INTO vainglory_part_jobs('
            'part_id,session_id,state,request_kind,progress,algorithm_version,'
            'match_count,error,requested_at,started_at,completed_at,updated_at) '
            'VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',
            (
                404,
                202,
                'pending',
                'manual',
                0,
                vainglory.ALGORITHM_VERSION,
                0,
                None,
                1,
                None,
                None,
                1,
            ),
        )
        await target.execute(
            'INSERT INTO vainglory_manual_match_markers('
            'id,session_id,part_id,at_ms,source,created_at,updated_at) '
            'VALUES(?,?,?,?,?,?,?)',
            (501, 202, 404, 900, 'dashboard', 1, 1),
        )
        await target.execute(
            'INSERT INTO vainglory_manual_match_markers('
            'id,session_id,part_id,at_ms,source,created_at,updated_at) '
            'VALUES(?,?,?,?,?,?,?)',
            (502, 202, 404, 100, 'dashboard', 1, 1),
        )
        scan_claim = await vainglory.claim_next(discover=False)
        assert scan_claim is not None
        assert scan_claim.part.manual_candidate_times_ms == (100, 900)
        await target.execute(
            'INSERT INTO vainglory_ocr_jobs('
            'part_id,session_id,state,video_duration_ms,candidate_times_json,'
            'candidate_count,requested_at,started_at,updated_at) '
            "VALUES(?,?,\'pending\',?,?,?,?,NULL,?)",
            (404, 202, 1_000, '[100]', 1, 1, 1),
        )
        ocr_claim = await vainglory.claim_next_ocr()
        assert ocr_claim is not None
        assert ocr_claim.part.id == 404
        archive = VisitorAnalyticsArchive(target)
        archive_status = await archive.status()
        now = datetime.now(timezone.utc)
        archive_summary = await archive.summary(
            VisitorAnalyticsQuery(
                start_at=now - timedelta(days=1), end_at=now, event='all'
            ),
            VisitorAnalyticsConfig(None, None),
            generated_at=now,
            status=archive_status,
        )
        assert archive_summary.totals.events == 0
        with pytest.raises(sqlite3.IntegrityError):
            await target.execute(
                'INSERT INTO vainglory_players('
                'name,origin,created_at,updated_at) VALUES(?,?,?,?)',
                (' invalid ', 'manual', 1, 1),
            )
    finally:
        await target.close()
