from typing import Union

from .models import (
    CoverImageDownloadedEvent,
    CoverImageDownloadedEventData,
    DanmakuFileCompletedEvent,
    DanmakuFileCompletedEventData,
    DanmakuFileCreatedEvent,
    DanmakuFileCreatedEventData,
    Error,
    ErrorData,
    LiveBeganEvent,
    LiveBeganEventData,
    LiveEndedEvent,
    LiveEndedEventData,
    PostprocessingCompletedEvent,
    PostprocessingCompletedEventData,
    RawDanmakuFileCompletedEvent,
    RawDanmakuFileCompletedEventData,
    RawDanmakuFileCreatedEvent,
    RawDanmakuFileCreatedEventData,
    RecordingCancelledEvent,
    RecordingCancelledEventData,
    RecordingFinishedEvent,
    RecordingFinishedEventData,
    RecordingStartedEvent,
    RecordingStartedEventData,
    RoomChangeEvent,
    RoomChangeEventData,
    SpaceNoEnoughEvent,
    SpaceNoEnoughEventData,
    VideoFileCompletedEvent,
    VideoFileCompletedEventData,
    VideoFileCreatedEvent,
    VideoFileCreatedEventData,
    VideoPostprocessingCompletedEvent,
    VideoPostprocessingCompletedEventData,
)

Event = Union[
    LiveBeganEvent,
    LiveEndedEvent,
    RoomChangeEvent,
    RecordingStartedEvent,
    RecordingFinishedEvent,
    RecordingCancelledEvent,
    VideoFileCreatedEvent,
    VideoFileCompletedEvent,
    DanmakuFileCreatedEvent,
    DanmakuFileCompletedEvent,
    RawDanmakuFileCreatedEvent,
    RawDanmakuFileCompletedEvent,
    CoverImageDownloadedEvent,
    VideoPostprocessingCompletedEvent,
    PostprocessingCompletedEvent,
    SpaceNoEnoughEvent,
    Error,
]

EventData = Union[
    LiveBeganEventData,
    LiveEndedEventData,
    RoomChangeEventData,
    RecordingStartedEventData,
    RecordingFinishedEventData,
    RecordingCancelledEventData,
    VideoFileCreatedEventData,
    VideoFileCompletedEventData,
    DanmakuFileCreatedEventData,
    DanmakuFileCompletedEventData,
    RawDanmakuFileCreatedEventData,
    RawDanmakuFileCompletedEventData,
    CoverImageDownloadedEventData,
    VideoPostprocessingCompletedEventData,
    PostprocessingCompletedEventData,
    SpaceNoEnoughEventData,
    ErrorData,
]
