import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  BellOutline,
  BarChartOutline,
  CloudDownloadOutline,
  CloudUploadOutline,
  ClusterOutline,
  CopyOutline,
  DashboardOutline,
  DatabaseOutline,
  DollarCircleOutline,
  GlobalOutline,
  HistoryOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MoreOutline,
  OrderedListOutline,
  QuestionCircleOutline,
  RedoOutline,
  ReloadOutline,
  SafetyCertificateOutline,
  SearchOutline,
  ScissorOutline,
  StarOutline,
  SwapOutline,
  TrophyOutline,
  UnorderedListOutline,
  UserOutline,
  VideoCameraOutline,
} from '@ant-design/icons-angular/icons';

const icons = [
  BellOutline,
  BarChartOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MoreOutline,
  DashboardOutline,
  GlobalOutline,
  ClusterOutline,
  HistoryOutline,
  OrderedListOutline,
  CloudDownloadOutline,
  CloudUploadOutline,
  CopyOutline,
  DatabaseOutline,
  DollarCircleOutline,
  QuestionCircleOutline,
  RedoOutline,
  ReloadOutline,
  SafetyCertificateOutline,
  SearchOutline,
  ScissorOutline,
  StarOutline,
  SwapOutline,
  TrophyOutline,
  UnorderedListOutline,
  UserOutline,
  VideoCameraOutline,
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {}
